@baseUrl = http://localhost:3000
@contentType = application/json
@authToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGViNWJmZi05ZmJhLTRjNWItOTI4MC0wMzIyMDE4MzM3ZGEiLCJlbWFpbCI6Im1lbGlzc2FtYWtlYmFAZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzUxOTA5NjQyLCJleHAiOjE3NTE5MTMyNDJ9.seTlmdTCuC5sd1o3CtvN6waa2Mvg2OLcFIH01k4M8Ck

### Register a new student
# @name register
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
  "firstName": "Kim",
  "lastName": "Now",
  "email": "yeloh19487@fuasha.com",
  "password": "Passw123",
  "confirmPassword": "Passw123"
}


### Login with credentials
# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "yeloh19487@fuasha.com",
  "password": "Passw123"
}


### Register an instructor
# @name registerInstructor
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
  "firstName": "Mel",
  "lastName": "User",
  "email": "melissa.waitituh@strathmore.edu",
  "password": "Const4321",
  "confirmPassword": "Const4321",
  "role": "INSTRUCTOR"
}

### Login with credentials
# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "melissa.waitituh@strathmore.edu",
  "password": "Const4321"
}

### Register an admin (if allowed)
# @name registerAdmin
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
  "firstName": "Admin",
  "lastName": "User",
  "email": "melissamakeba@gmail.com",
  "password": "Password123",
  "confirmPassword": "Password123",
  "role": "ADMIN"
}

### Login with credentials
# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "melissamakeba@gmail.com",
  "password": "ToxiC789"
}

### Verify email
POST {{baseUrl}}/auth/verify-email
Content-Type: {{contentType}}

{
  "token": "942261"
}

### Forgot password
POST {{baseUrl}}/auth/forgot-password
Content-Type: {{contentType}}

{
  "email": "melissamakeba@gmail.com"
}

### Reset password
POST {{baseUrl}}/auth/reset-password
Content-Type: {{contentType}}

{
  "token": "785619",
  "password": "ToxiC789",
  "confirmPassword": "ToxiC789"
}

### Refresh token
POST {{baseUrl}}/auth/refresh-token
Content-Type: {{contentType}}

{
  "refreshToken": " "
}

### Logout
POST {{baseUrl}}/auth/logout
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}