@baseUrl = http://localhost:3000
@contentType = application/json

### Variables
@authToken = 

### Register a new user
# @name register
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
  "firstName": "Glass",
  "lastName": "Gow",
  "email": "glass.gow@gmail.com",
  "password": "Password123",
  "confirmPassword": "Password123"
}

### Register an instructor
# @name registerInstructor
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
  "firstName": "Mel",
  "lastName": "User",
  "email": "mellisawanja254@gmail.com",
  "password": "Chinje123",
  "confirmPassword": "Chinje123",
  "role": "STUDENT"
}

### Register an admin (if allowed)
# @name registerAdmin
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
  "firstName": "Admin",
  "lastName": "User",
  "email": "melissamakeba@gmail.com",
  "password": "Password123",
  "confirmPassword": "Password123",
  "role": "ADMIN"
}

### Login with credentials
# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "mellisawanja254@gmail.com",
  "password": "Toxic321"
}

### Verify email
POST {{baseUrl}}/auth/verify-email
Content-Type: {{contentType}}

{
  "token": "171732"
}

### Forgot password
POST {{baseUrl}}/auth/forgot-password
Content-Type: {{contentType}}

{
  "email": "mellisawanja254@gmail.com"
}

### Reset password
POST {{baseUrl}}/auth/reset-password
Content-Type: {{contentType}}

{
  "token": "301737",
  "password": "Toxic321",
  "confirmPassword": "Toxic321"
}

### Refresh token
POST {{baseUrl}}/auth/refresh-token
Content-Type: {{contentType}}

{
  "refreshToken": " "
}

### Logout
POST {{baseUrl}}/auth/logout
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}